const children = [
    {
    "surname": "Valvason",
    "name": "Liam",
    "dateOfBirth": "11/20/2015",
    "school": "",
    "level": "",
    "street": "Rue profonde 27",
    "postalCode": "1970",
    "city": "Wezembeek oppem",
    "contact1": "Mouna	Berbit",
    "tel1": "0486608703",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15112025551",
    "email": "mouna_berbit@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Arango",
    "name": "Isabella",
    "dateOfBirth": "02/04/2019",
    "school": "",
    "level": "",
    "street": "Avenue de Broqueville 242 boite 15",
    "postalCode": "1200",
    "city": "Woluwe saint lambert",
    "contact1": "Gloria	Arango",
    "field12": "",
    "tel1": "0489755015",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19020426458",
    "email": "glo.arango@outlook.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pierlot",
    "name": "Juliette",
    "dateOfBirth": "08/15/2012",
    "school": "",
    "level": "",
    "street": "Medaetsstraat, 60",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Alla Robertovna	Epremyan",
    "field12": "",
    "tel1": "0486335975",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12.08.15-054.27",
    "email": "alla_epremyan@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pierlot",
    "name": "Mathieu",
    "dateOfBirth": "12/05/2016",
    "school": "",
    "level": "",
    "street": "Medaetsstraat, 60",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Alla Robertovna	Epremyan",
    "field12": "",
    "tel1": "0486335975",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.12.05-181.21",
    "email": "alla_epremyan@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pierlot",
    "name": "St�phanie",
    "dateOfBirth": "08/23/2018",
    "school": "",
    "level": "",
    "street": "Medaetsstraat, 60",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Alla Robertovna	Epremyan",
    "field12": "",
    "tel1": "0486335975",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18.08.23-084.77",
    "email": "alla_epremyan@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pierlot",
    "name": "Laurence",
    "dateOfBirth": "02/10/2020",
    "school": "",
    "level": "",
    "street": "Medaetsstraat, 60",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Alla Robertovna	Epremyan",
    "field12": "",
    "tel1": "0486335975",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20.02.10-030.36",
    "email": "alla_epremyan@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Ranaivoson",
    "name": "Lydia",
    "dateOfBirth": "08/07/2016",
    "school": "",
    "level": "",
    "street": "Ave Charles Thielemans 102 bte 1",
    "postalCode": "1150",
    "city": "Woluwe saint pierre",
    "contact1": "Yusha	Jadidi",
    "field12": "",
    "tel1": "0474329445",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16080711695",
    "email": "yushajadidi@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Kamel",
    "name": "Ka�s",
    "dateOfBirth": "02/21/2017",
    "school": "",
    "level": "",
    "street": "Rue veydt 71",
    "postalCode": "1050",
    "city": "Ixelles",
    "contact1": "Morad	Kamel",
    "field12": "",
    "tel1": "0487931788",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "170221-24114",
    "email": "kamel.morad.mk@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Kamel",
    "name": "Ma�ssa",
    "dateOfBirth": "02/21/2017",
    "school": "",
    "level": "",
    "street": "Rue veydt 71",
    "postalCode": "1050",
    "city": "Ixelles",
    "contact1": "Morad	Kamel",
    "field12": "",
    "tel1": "0487931788",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "170221-172.83",
    "email": "kamel.morad.mk@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Timmer",
    "name": "William",
    "dateOfBirth": "06/27/2018",
    "school": "",
    "level": "",
    "street": "Avenue de Calabre 10 Boite 14",
    "postalCode": "1200",
    "city": "Woluwe St lambert",
    "contact1": "Lauren	Somer",
    "field12": "",
    "tel1": "0495634307",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "81091527470",
    "email": "laurensomer@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Meurice",
    "name": "Enis",
    "dateOfBirth": "04/03/2017",
    "school": "",
    "level": "",
    "street": "Avenue Reine Astrid 468",
    "postalCode": "1950",
    "city": "Kraainem",
    "contact1": "Duygu	Kara",
    "field12": "",
    "tel1": "0472214992",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17040309535",
    "email": "karaduygu@hotmail.be",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "SCHEYVAERTS",
    "name": "JOANNE",
    "dateOfBirth": "12/02/2015",
    "school": "",
    "level": "",
    "street": "312 AV LOUIS JASMINLAAN",
    "postalCode": "1150",
    "city": "BRUXELLES",
    "contact1": "STEPHANIE EN ARNAUD	SCHEYVAERTS MANGEZ",
    "field12": "",
    "tel1": "0479413234",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15120216014",
    "email": "arnaudetsteph@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Visart",
    "name": "Timothy",
    "dateOfBirth": "10/18/2016",
    "school": "",
    "level": "",
    "street": "Chaussee de wavre 906/12 a 1040 Bruxelles",
    "postalCode": "1040",
    "city": "Bruxelles",
    "contact1": "Maud	Visart",
    "field12": "",
    "tel1": "0470852426",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16101836911",
    "email": "maudvisart@yhoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Passelecq",
    "name": "Gabin",
    "dateOfBirth": "04/25/2011",
    "school": "",
    "level": "",
    "street": "Medaetsstraat 62",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Laurent	Passelecq",
    "field12": "",
    "tel1": "0479/97 20 14",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "11.04.25-217.97",
    "email": "laurent.passelecq@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Passelecq",
    "name": "Matthieu",
    "dateOfBirth": "07/23/2012",
    "school": "",
    "level": "",
    "street": "Medaetsstraat 62",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Laurent	Passelecq",
    "field12": "",
    "tel1": "0479/97 20 14",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12.07.23-167.55",
    "email": "laurent.passelecq@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Passelecq",
    "name": "Maxime",
    "dateOfBirth": "04/17/2014",
    "school": "",
    "level": "",
    "street": "Medaetsstraat 62",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Laurent	Passelecq",
    "field12": "",
    "tel1": "0479/97 20 14",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14.04.17-243.83",
    "email": "laurent.passelecq@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "van Gruijthuijsen",
    "name": "Pieter",
    "dateOfBirth": "3/10/1024",
    "school": "",
    "level": "",
    "street": "Oppemlaan 100",
    "postalCode": "1970",
    "city": "wezembeek oppem",
    "contact1": "Susanna	Di Feliciantonio",
    "field12": "",
    "tel1": "0486-502611",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14.03.10 203-35",
    "email": "johanvangruijt@outlook.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "van Gruijthuijsen",
    "name": "Thomas",
    "dateOfBirth": "04/23/2016",
    "school": "",
    "level": "",
    "street": "Oppemlaan 100",
    "postalCode": "1970",
    "city": "wezembeek oppem",
    "contact1": "Susanna	Di Feliciantonio",
    "field12": "",
    "tel1": "0486-502611",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.04.23 037-54",
    "email": "johanvangruijt@outlook.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Kaushal",
    "name": "Paarkhi",
    "dateOfBirth": "06/15/2018",
    "school": "",
    "level": "",
    "street": "Avenue des grands prix 114, Box 6, Woluwe-Saint-Pierre",
    "postalCode": "1150",
    "city": "Woluwe-Saint-Pierre",
    "contact1": "Sudhansh	Kaushal",
    "field12": "",
    "tel1": "0476860427",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "220454",
    "email": "sudhanshk1988@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Calle Valencia",
    "name": "Talyana",
    "dateOfBirth": "08/16/2010",
    "school": "",
    "level": "",
    "street": "Puttestraat 43",
    "postalCode": "3080",
    "city": "Tervuren",
    "contact1": "Claudia	Virgone",
    "field12": "",
    "tel1": "0476479898",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "10081628020",
    "email": "clvirgone@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Calle Valencia",
    "name": "Reynaldo",
    "dateOfBirth": "02/25/2012",
    "school": "",
    "level": "",
    "street": "Puttestraat 47",
    "postalCode": "3080",
    "city": "Tervuren",
    "contact1": "Claudia	Virgone",
    "field12": "",
    "tel1": "0476479898",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12022521113",
    "email": "clvirgone@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Van Maercke",
    "name": "Emilie",
    "dateOfBirth": "05/21/2020",
    "school": "",
    "level": "",
    "street": "Konkelstraat 103, 7e",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Serena 	Azzi",
    "field12": "",
    "tel1": "0472984620",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20.05.21-006.42",
    "email": "serena.azzi@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "NGANSINY",
    "name": "Nolan",
    "dateOfBirth": "05/18/2018",
    "school": "",
    "level": "",
    "street": "Mercuriusstraat 5 / 013",
    "postalCode": "1930",
    "city": "Zaventem",
    "contact1": "Richelle	Ndingambote-Nzala",
    "field12": "",
    "tel1": "0465953163",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18051828901",
    "email": "richellendingambotenzala@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Brandhof",
    "name": "Michael",
    "dateOfBirth": "01/03/2019",
    "school": "",
    "level": "",
    "street": "Priester de l'Ep�estraat, 17",
    "postalCode": "1200",
    "city": "Brussel",
    "contact1": "Alexandre	Brandhof",
    "field12": "",
    "tel1": "+32492150521",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19.01.03 105-46",
    "email": "Alexandre.Brandhof@Gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hylebos",
    "name": "C�zanne",
    "dateOfBirth": "05/05/2019",
    "school": "",
    "level": "",
    "street": "Georges Henrilaan 4",
    "postalCode": "1200",
    "city": "Sint-Lambrechts-Woluwe",
    "contact1": "Charline	Daelman",
    "field12": "",
    "tel1": "0474377031",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19050509821",
    "email": "charline_daelman@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hylebos",
    "name": "Astor",
    "dateOfBirth": "01/06/2016",
    "school": "",
    "level": "",
    "street": "Georges Henrilaan 4",
    "postalCode": "1200",
    "city": "Sint-Lambrechts-Woluwe",
    "contact1": "Charline	Daelman",
    "field12": "",
    "tel1": "0474377031",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16060135918",
    "email": "charline_daelman@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pislaru",
    "name": "Vlad-Alexandru",
    "dateOfBirth": "03/19/2018",
    "school": "",
    "level": "",
    "street": "Jean Monnetlaan, 10",
    "postalCode": "1200",
    "city": "Brussels",
    "contact1": "Catalina	Pislaru",
    "field12": "",
    "tel1": "0478381523",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18031922323",
    "email": "catalinapislaru@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Pislaru",
    "name": "Nadia",
    "dateOfBirth": "02/23/2020",
    "school": "",
    "level": "",
    "street": "Jean Monnetlaan 10",
    "postalCode": "1200",
    "city": "Brussels",
    "contact1": "Catalina	Pislaru",
    "field12": "",
    "tel1": "0478381523",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20022312833",
    "email": "catalinapislaru@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Tabibi",
    "name": "Rawan",
    "dateOfBirth": "08/10/2019",
    "school": "",
    "level": "",
    "street": "Rue des Coteaux 188 bo�te 6",
    "postalCode": "1030",
    "city": "Bruxelles",
    "contact1": "Abdelkader	Tabibi",
    "field12": "",
    "tel1": "0488888566",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19081008007",
    "email": "abdel0219@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hammou",
    "name": "Ilias",
    "dateOfBirth": "05/14/2017",
    "school": "",
    "level": "",
    "street": "Schransdreef 53",
    "postalCode": "3090",
    "city": "OVERIJSE",
    "contact1": "Sophie 	Dellache",
    "field12": "",
    "tel1": "0483 414 771",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "170514 211 81",
    "email": "so_ph_2507@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hammou",
    "name": "Lya",
    "dateOfBirth": "05/27/2012",
    "school": "",
    "level": "",
    "street": "Schransdreef 53",
    "postalCode": "3090",
    "city": "Overijse",
    "contact1": "Sophie 	Dellache",
    "field12": "",
    "tel1": "0483 414 771",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "120527 186 96",
    "email": "so_ph_2507@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hammou",
    "name": "�lyne",
    "dateOfBirth": "06/14/2015",
    "school": "",
    "level": "",
    "street": "Schransdreef 53",
    "postalCode": "3090",
    "city": "Overijse",
    "contact1": "Sophie 	Dellache",
    "field12": "",
    "tel1": "Schransdreef 53",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "150614 154 06",
    "email": "so_ph_2507@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Rajagopal",
    "name": "Prabhu",
    "dateOfBirth": "08/09/2019",
    "school": "",
    "level": "",
    "street": "Th�odore de Cuypersstraat 123/1",
    "postalCode": "1200",
    "city": "Sint-Lambrechts-Woluwe",
    "contact1": "Prabhu	Rajagopal",
    "field12": "",
    "tel1": "0485/949688",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19.08.09-119-95",
    "email": "prabhu_rajagopal@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Amezian",
    "name": "Amina",
    "dateOfBirth": "08/17/2017",
    "school": "",
    "level": "",
    "street": "Henri Lafontainelaan 49 b50",
    "postalCode": "1600",
    "city": "Brussel",
    "contact1": "Sanae	Tarfous",
    "field12": "",
    "tel1": "+32486679428",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "1708201728215",
    "email": "sanaetarfous@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Tangarife Valencia",
    "name": "Esmeralda",
    "dateOfBirth": "09/07/2017",
    "school": "",
    "level": "",
    "street": "Avenue des Jacinthes 11",
    "postalCode": "1030",
    "city": "Brussel",
    "contact1": "Jaime 	Tangarife Valencia",
    "field12": "",
    "tel1": "04 85 84 12 77",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17090738647",
    "email": "j.tangarifevalencia@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Tangarife Valencia",
    "name": "Santiago",
    "dateOfBirth": "02/09/2016",
    "school": "",
    "level": "",
    "street": "Avenue des Jacinthes 11",
    "postalCode": "1030",
    "city": "Brussel",
    "contact1": "Jaime 	Tangarife Valencia",
    "field12": "",
    "tel1": "04 85 84 12 77",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "160209307993",
    "email": "j.tangarifevalencia@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Sbai filali",
    "name": "Chadine",
    "dateOfBirth": "04/05/2013",
    "school": "",
    "level": "",
    "street": "Schapulierstraat 17",
    "postalCode": "1800",
    "city": "Vilvoorde",
    "contact1": "Shahinaze 	Benaissa",
    "field12": "",
    "tel1": "0485932435/ 0488194438",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "130405-31856",
    "email": "shahiben@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Sbai filali",
    "name": "Chadine",
    "dateOfBirth": "04/05/2013",
    "school": "",
    "level": "",
    "street": "Schapulierstraat 17",
    "postalCode": "1800",
    "city": "Vilvoorde",
    "contact1": "Shahinaze 	Benaissa",
    "field12": "",
    "tel1": "0485932435/ 0488194438",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "130405-31856",
    "email": "shahiben@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Sbai filali",
    "name": "Fyri�l",
    "dateOfBirth": "12/02/2015",
    "school": "",
    "level": "",
    "street": "Schapulierstraat 17",
    "postalCode": "1800",
    "city": "Vilvoorde",
    "contact1": "Shahinaze 	Benaissa",
    "field12": "",
    "tel1": "0485932435/ 0488194438",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "151202-26803",
    "email": "shahiben@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "van maercke",
    "name": "emilie",
    "dateOfBirth": "05/21/2020",
    "school": "",
    "level": "",
    "street": "Konkelstraat 103",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Serena	Azzi",
    "field12": "",
    "tel1": "0472984620",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20052100642",
    "email": "serena.azzi@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Moens",
    "name": "Lexi",
    "dateOfBirth": "11/12/2012",
    "school": "",
    "level": "",
    "street": "Wezembeek-Oppem",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem - 1970",
    "contact1": "Anouk	Inozu",
    "field12": "",
    "tel1": "+32 475 50  35 82",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "121112-15042",
    "email": "ainozu@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Courtin",
    "name": "Olivia",
    "dateOfBirth": "02/20/2018",
    "school": "",
    "level": "",
    "street": "rue andre crabbe 10",
    "postalCode": "1200",
    "city": "Bruxelles",
    "contact1": "aurore	Duyzings",
    "field12": "",
    "tel1": "0479302996",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "180322264856",
    "email": "aurore.duyzings@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Courtin",
    "name": "James",
    "dateOfBirth": "01/08/2015",
    "school": "",
    "level": "",
    "street": "rue andre crabbe 10",
    "postalCode": "1200",
    "city": "Bruxelles",
    "contact1": "Aurore	Duyzings",
    "field12": "",
    "tel1": "0479302996",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15080101960",
    "email": "aurore.duyzings@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Zaki",
    "name": "Amir",
    "dateOfBirth": "08/19/2010",
    "school": "",
    "level": "",
    "street": "Chauss�e de Boondael 514",
    "postalCode": "1050",
    "city": "Bruxelles",
    "contact1": "Houda 	Marrun",
    "field12": "",
    "tel1": "0485127556",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "10081930502",
    "email": "hodet25@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Blasson",
    "name": "Elise",
    "dateOfBirth": "08/23/2012",
    "school": "",
    "level": "",
    "street": "Grensstraat 51",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Nathalie	De Schepper",
    "field12": "",
    "tel1": "0499261871",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12082325868",
    "email": "nathaliedeschepper@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Blasson",
    "name": "Charles",
    "dateOfBirth": "06/23/2014",
    "school": "",
    "level": "",
    "street": "Grensstraat 51",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Nathalie	De Schepper",
    "field12": "",
    "tel1": "0499261871",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14062318374",
    "email": "nathaliedeschepper@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Noiret Vanneste",
    "name": "Gaspard",
    "dateOfBirth": "05/28/2019",
    "school": "",
    "level": "",
    "street": "Rue des Bannieres 18",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Aurelie	Noiret",
    "field12": "",
    "tel1": "0499858314",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19052807731",
    "email": "aure.noiret@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Andres",
    "name": "Cyriac",
    "dateOfBirth": "07/25/2019",
    "school": "",
    "level": "",
    "street": "Weggevoerdenstraat 77",
    "postalCode": "1200",
    "city": "Sint-Lambrechts-Woluwe",
    "contact1": "Christophe 	Andres",
    "field12": "",
    "tel1": "0479691784",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19072508926",
    "email": "andreschristophe@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "de Montjoye",
    "name": "Maurice",
    "dateOfBirth": "08/30/2016",
    "school": "",
    "level": "",
    "street": "Clos de la foret 8",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Victoria	de Montjoye",
    "field12": "",
    "tel1": "0474861625",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.08.30-296.28",
    "email": "victoriagoethals@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "de Montjoye",
    "name": "L�on",
    "dateOfBirth": "02/11/2018",
    "school": "",
    "level": "",
    "street": "Clos de la foret 8",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Victoria	de Montjoye",
    "field12": "",
    "tel1": "0474861625",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18.02.05-051.26",
    "email": "victoriagoethals@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Fabri d�Enneilles Gim�nez",
    "name": "Victoria",
    "dateOfBirth": "01/26/2018",
    "school": "",
    "level": "",
    "street": "Tomberg 193",
    "postalCode": "1200",
    "city": "Sint Lambrechts Woluwe",
    "contact1": "Carlota	Gim�nez Calvo",
    "field12": "",
    "tel1": "0486570567",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18.01.26-066.53",
    "email": "carlota.gimenezcalvo@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Golinvaux",
    "name": "Norah",
    "dateOfBirth": "06/02/2015",
    "school": "",
    "level": "",
    "street": "Clos du manoir 5",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Natalia	Bustos",
    "field12": "",
    "tel1": "0479525683",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15060232402",
    "email": "agila_nb@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Golinvaux",
    "name": "Nicolas",
    "dateOfBirth": "06/25/2019",
    "school": "",
    "level": "",
    "street": "Clos du manoir 5",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Natalia	Bustos",
    "field12": "",
    "tel1": "0479525683",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19062521587",
    "email": "agila_nb@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Golinvaux",
    "name": "Norah",
    "dateOfBirth": "06/02/2015",
    "school": "",
    "level": "",
    "street": "Clos du manoir 5",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Natalia	Bustos",
    "field12": "",
    "tel1": "0479525683",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15060232402",
    "email": "agila_nb@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Golinvaux",
    "name": "Nicolas",
    "dateOfBirth": "06/25/2019",
    "school": "",
    "level": "",
    "street": "clos du manoir 5",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Natalia	Bustos",
    "field12": "",
    "tel1": "0479525683",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19062521587",
    "email": "agila_nb@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Lhawang youdon",
    "name": "TENZIN",
    "dateOfBirth": "10/08/2015",
    "school": "",
    "level": "",
    "street": "Rue VERHEYLEWEGHEN 11",
    "postalCode": "1200",
    "city": "Woluwe-Saint-lambere",
    "contact1": "Dechen 	NGAWANG",
    "field12": "",
    "tel1": "0466491593",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15.08.10-040.60",
    "email": "lgonpo88@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Dreher",
    "name": "Elena",
    "dateOfBirth": "07/15/2015",
    "school": "",
    "level": "",
    "street": "Atlantische Oceaanlaan 93",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Mattias	Dreher",
    "field12": "",
    "tel1": "0498120243",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15071508255",
    "email": "mdreher@global-fairs.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Dreher",
    "name": "Sofia",
    "dateOfBirth": "04/15/2017",
    "school": "",
    "level": "",
    "street": "Atlantische Oceaanlaan 93",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Mattias	Dreher",
    "field12": "",
    "tel1": "0498120243",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17041513226",
    "email": "mdreher@global-fairs.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Dreher",
    "name": "William",
    "dateOfBirth": "01/05/2020",
    "school": "",
    "level": "",
    "street": "Atlantische Oceaanlaan 93",
    "postalCode": "1150",
    "city": "Sint-Pieters-Woluwe",
    "contact1": "Mattias	Dreher",
    "field12": "",
    "tel1": "0498120243",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20010519910",
    "email": "mdreher@global-fairs.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Dolkar Yangzom",
    "name": "Palmo",
    "dateOfBirth": "09/13/2014",
    "school": "",
    "level": "",
    "street": "Avenue Milcamps 209",
    "postalCode": "1030",
    "city": "Bruxelles",
    "contact1": "Selina 	Dolkar Yangzom",
    "field12": "",
    "tel1": "0493303402",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14.09.13-220.67",
    "email": "yangzomdol1314@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "ARITON",
    "name": "Mara",
    "dateOfBirth": "09/21/2013",
    "school": "",
    "level": "",
    "street": "Paul Hymans Laan nr 83",
    "postalCode": "1200",
    "city": "Sint Lambrechts Woluwe",
    "contact1": "Oana	Ariton",
    "field12": "",
    "tel1": "0485499016",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "13092127443",
    "email": "ogogioiu@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "ARITON",
    "name": "Petra",
    "dateOfBirth": "07/18/2017",
    "school": "",
    "level": "",
    "street": "Paul Hymans Laan nr 83",
    "postalCode": "1200",
    "city": "Sint Lambrechts Woluwe",
    "contact1": "Oana	Ariton",
    "field12": "",
    "tel1": "0485499016",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17071839087",
    "email": "ogogioiu@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Brouwers-Morelle",
    "name": "Thibaud",
    "dateOfBirth": "09/18/2018",
    "school": "",
    "level": "",
    "street": "Avenue Jules deTrooz 36/5",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Anne-Claire 	Morelle",
    "field12": "",
    "tel1": "0478 22 84 58",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "180918-199.22",
    "email": "a.c.morelle@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Fabri d�Enneilles Gim�nez",
    "name": "Gabriel",
    "dateOfBirth": "04/21/2015",
    "school": "",
    "level": "",
    "street": "Tomberg 193",
    "postalCode": "1200",
    "city": "Sint Lambrechts Woluwe",
    "contact1": "Carlota	Gim�nez Calvo",
    "field12": "",
    "tel1": "0486570567",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15.04.21-099.31",
    "email": "carlota.gimenezcalvo@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Debroux",
    "name": "Ella",
    "dateOfBirth": "05/06/2018",
    "school": "",
    "level": "",
    "street": "TOMBERG 116",
    "postalCode": "1200",
    "city": "SINT LAMBRECHTS WOLUWE",
    "contact1": "LAURENCE	DEBROUX",
    "field12": "",
    "tel1": "0470934593",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18050608679",
    "email": "laurencedebroux@me.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Timmer",
    "name": "William",
    "dateOfBirth": "07/06/2018",
    "school": "",
    "level": "",
    "street": "Avenue de Calabre 10 Boite 14",
    "postalCode": "1200",
    "city": "Sint Lambrechts Woluwe",
    "contact1": "Lauren	Somer",
    "field12": "",
    "tel1": "0495634307",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "2021/0637",
    "email": "laurensomer@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nguyen",
    "name": "Ngoc Minh",
    "dateOfBirth": "07/22/2012",
    "school": "",
    "level": "",
    "street": "Avenue des Dames Blanches, 51",
    "postalCode": "1150",
    "city": "Brussels",
    "contact1": "Thanh Ngoc	Tran",
    "field12": "",
    "tel1": "0479123911",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12.07.22-112-43",
    "email": "tthanhngoc@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nguyen",
    "name": "Ngoc Que",
    "dateOfBirth": "12/24/2014",
    "school": "",
    "level": "",
    "street": "avenue des Dames Blanches, 51",
    "postalCode": "1150",
    "city": "Brussels",
    "contact1": "Thanh Ngoc	Tran",
    "field12": "",
    "tel1": "0479123911",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14.12.24-264-05",
    "email": "tthanhngoc@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nguyen",
    "name": "Ngoc Han",
    "dateOfBirth": "12/24/2014",
    "school": "",
    "level": "",
    "street": "avenue des Dames Blanches, 51",
    "postalCode": "1150",
    "city": "Brussels",
    "contact1": "Thanh Ngoc	Tran",
    "field12": "",
    "tel1": "0479123911",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14.12.24-262-07",
    "email": "tthanhngoc@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Franssens",
    "name": "Gabriel",
    "dateOfBirth": "06/07/2015",
    "school": "",
    "level": "",
    "street": "Bosstraat 295",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Margot	de Kerchove",
    "field12": "",
    "tel1": "0473729929",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15060718588",
    "email": "margotdekerchove@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Franssens",
    "name": "Lys",
    "dateOfBirth": "10/26/2019",
    "school": "",
    "level": "",
    "street": "Bosstraat 295",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Margot	de Kerchove",
    "field12": "",
    "tel1": "0473729929",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19102610697",
    "email": "margotdekerchove@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "KADIOGLU",
    "name": "ALISA ALIYE",
    "dateOfBirth": "02/15/2017",
    "school": "",
    "level": "",
    "street": "AVENUE JULES CESAR 14",
    "postalCode": "1150",
    "city": "WOLUWE-SAINT-PIERRE (BRUXELLES)",
    "contact1": "HULYA	KADIOGLU",
    "field12": "",
    "tel1": "+32 (0) 471 76 90 19",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17021507866",
    "email": "dioka.kan@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Boulahya",
    "name": "Imran",
    "dateOfBirth": "01/11/2012",
    "school": "",
    "level": "",
    "street": "Keizer Karellaan 4",
    "postalCode": "1982",
    "city": "Elewijt",
    "contact1": "Kenza	Berbit",
    "field12": "",
    "tel1": "0485/54/62-09",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12011118960",
    "email": "kenouza85@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Boulahya",
    "name": "Yanis",
    "dateOfBirth": "11/06/2013",
    "school": "",
    "level": "",
    "street": "Keizer Karellaan 4",
    "postalCode": "1982",
    "city": "Elewijt",
    "contact1": "Kenza 	Berbit",
    "field12": "",
    "tel1": "0485546209",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "13110615940",
    "email": "kenouza85@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Boulahya",
    "name": "Dalil",
    "dateOfBirth": "02/12/2017",
    "school": "",
    "level": "",
    "street": "Keizer Karellaan 4",
    "postalCode": "1982",
    "city": "Elewijt",
    "contact1": "Kenza 	Berbit",
    "field12": "",
    "tel1": "0485546209",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17021215579",
    "email": "kenouza85@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Verhoestraete",
    "name": "Eliam",
    "dateOfBirth": "04/27/2019",
    "school": "",
    "level": "",
    "street": "Rue Th�odore de Cuyper 165/12",
    "postalCode": "1200",
    "city": "Bruxelles",
    "contact1": "Fabian	Verhoestraete",
    "field12": "",
    "tel1": "0496388004",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19.04.27-083.48",
    "email": "fabian.verhoestraete@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "voortman",
    "name": "Timoth�e",
    "dateOfBirth": "05/17/2018",
    "school": "",
    "level": "",
    "street": "Saffierstraat 22",
    "postalCode": "1030",
    "city": "Schaarbeek",
    "contact1": "Geraldine 	Voortman",
    "field12": "",
    "tel1": "0477541422",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18051709729",
    "email": "gevoort@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Revelo",
    "name": "Bryant",
    "dateOfBirth": "06/16/2017",
    "school": "",
    "level": "",
    "street": "kleinenbergstraat 6",
    "postalCode": "1932",
    "city": "zaventem",
    "contact1": "cindy	kesteleyn",
    "field12": "",
    "tel1": "0484304080",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17061616772",
    "email": "cindy.kesteleyn@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "revelo",
    "name": "Luna Rosalie",
    "dateOfBirth": "07/14/2015",
    "school": "",
    "level": "",
    "street": "kleinenbergstraat 6",
    "postalCode": "1932",
    "city": "zaventem",
    "contact1": "cindy	kesteleyn",
    "field12": "",
    "tel1": "0484304080",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15071428675",
    "email": "cindy.kesteleyn@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Debaty",
    "name": "Janna�",
    "dateOfBirth": "10/20/2011",
    "school": "",
    "level": "",
    "street": "rue �douard Dekoster 10",
    "postalCode": "1140",
    "city": "Bruxelles",
    "contact1": "Liliane / Michel 	Denys / Geirnaert",
    "field12": "",
    "tel1": "0476.43.11.90 / 0475.74.51.47",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "11.10.20-302.10",
    "email": "liliane.denys@proximus.be",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Paul",
    "name": "Amandine",
    "dateOfBirth": "05/13/2015",
    "school": "",
    "level": "",
    "street": "Avenue de la perspective, 17",
    "postalCode": "1150",
    "city": "Woluwe-Saint-Pierre",
    "contact1": "Marie	Niemants",
    "field12": "",
    "tel1": "0473397485",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15051300482",
    "email": "marieniemants@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Paul",
    "name": "Juliette",
    "dateOfBirth": "02/17/2018",
    "school": "",
    "level": "",
    "street": "Avenue de la perspective, 17",
    "postalCode": "1150",
    "city": "Woluwe-Saint-Pierre",
    "contact1": "Marie	Niemants",
    "field12": "",
    "tel1": "0473397485",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18021706837",
    "email": "marieniemants@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "de Menten",
    "name": "Ana�s",
    "dateOfBirth": "10/15/2015",
    "school": "",
    "level": "",
    "street": "Fran�ois Peeterslaan, 7",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Julie	De Herde",
    "field12": "",
    "tel1": "0475266934",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15101526884",
    "email": "jdh154@yahoo.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "de Menten",
    "name": "Antoine",
    "dateOfBirth": "03/20/2020",
    "school": "",
    "level": "",
    "street": "Fran�ois Peeterslaan, 7",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Julie	De Herde",
    "field12": "",
    "tel1": "0475266934",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "20032017583",
    "email": "jdh154@yahoo.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Faouzi",
    "name": "Na�m",
    "dateOfBirth": "02/05/2017",
    "school": "",
    "level": "",
    "street": "Verdunstraat 203",
    "postalCode": "1130",
    "city": "Bruxelles",
    "contact1": "Sana	Jaoudi",
    "field12": "",
    "tel1": "0475389252",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17020509162",
    "email": "jaoudisana@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "HOANG",
    "name": "Phong David",
    "dateOfBirth": "01/24/2019",
    "school": "",
    "level": "",
    "street": "Avenue du Roi Chevalier 31",
    "postalCode": "1200",
    "city": "Woluwe-Saint-Lambert",
    "contact1": "Thanh Thuy	Phan thi",
    "field12": "",
    "tel1": "0485820089",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19012427918",
    "email": "thanh_thuy1994@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Gors",
    "name": "Isaure",
    "dateOfBirth": "04/18/2015",
    "school": "",
    "level": "",
    "street": "Avenue des ducs 30",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Isabelle 	Lethe",
    "field12": "",
    "tel1": "0474768157",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15011821482",
    "email": "isalethe@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Gors",
    "name": "Hortense",
    "dateOfBirth": "4/18/0018",
    "school": "",
    "level": "",
    "street": "Avenue des ducs 30",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Isabelle 	Gors",
    "field12": "",
    "tel1": "0474768157",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18041819687",
    "email": "isalethe@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Lamy",
    "name": "Amelie",
    "dateOfBirth": "07/07/2017",
    "school": "",
    "level": "",
    "street": "Rue gergel 88",
    "postalCode": "1970",
    "city": "Wezembeek Oppem",
    "contact1": "Sabine	Brillon",
    "field12": "",
    "tel1": "0479310084",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17070718837",
    "email": "sabine.brillon@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Lamy",
    "name": "Alix",
    "dateOfBirth": "01/30/2015",
    "school": "",
    "level": "",
    "street": "Rue gergel 88",
    "postalCode": "1970",
    "city": "Wezembeek Oppem",
    "contact1": "Sabine 	Brillon",
    "field12": "",
    "tel1": "0479310084",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15013024876",
    "email": "sabine.brillon@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hujoel",
    "name": "Nelson",
    "dateOfBirth": "12/06/2018",
    "school": "",
    "level": "",
    "street": "Rode Beukenlaan 8",
    "postalCode": "1970",
    "city": "WEZEMBEEK-OPPEM",
    "contact1": "Frederique	Nissen",
    "field12": "",
    "tel1": "0477567861",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18120605958",
    "email": "frederique.nissen@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Coduys",
    "name": "Amy",
    "dateOfBirth": "07/01/2012",
    "school": "",
    "level": "",
    "street": "Avenue Leopold III 89",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Magali	Deladrier",
    "field12": "",
    "tel1": "0492/463036",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "12070114261",
    "email": "magalideladrier@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Camara",
    "name": "Aboubacar",
    "dateOfBirth": "11/12/2015",
    "school": "",
    "level": "",
    "street": "Brandhoutkaii 37",
    "postalCode": "1000",
    "city": "Brussel",
    "contact1": "Sonia	BA",
    "field12": "",
    "tel1": "0465583751",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15111234309",
    "email": "soniaba2010@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Camara",
    "name": "Maymouna",
    "dateOfBirth": "06/02/2017",
    "school": "",
    "level": "",
    "street": "Brandhoutkaii 37",
    "postalCode": "1000",
    "city": "Brussel",
    "contact1": "Sonia	BA",
    "field12": "",
    "tel1": "0465583751",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17060239471",
    "email": "soniaba2010@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Hoang",
    "name": "Phong David",
    "dateOfBirth": "01/24/2019",
    "school": "",
    "level": "",
    "street": "Avenue du Roi Chevalier 31",
    "postalCode": "1200",
    "city": "Woluwe-Saint-Lambert",
    "contact1": "Thanh Thuy	Phan thi",
    "field12": "",
    "tel1": "0485820089",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "19012427918",
    "email": "thanh_thuy1994@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Adam",
    "name": "Leana",
    "dateOfBirth": "05/25/2011",
    "school": "",
    "level": "",
    "street": "Vosberg 38",
    "postalCode": "1970",
    "city": "Wezembeek-Oppem",
    "contact1": "Isabelle 	Reniers",
    "field12": "",
    "tel1": "0478678667",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "11052519412",
    "email": "Isaetade@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Abi Abdallah",
    "name": "Oscar",
    "dateOfBirth": "02/17/2017",
    "school": "",
    "level": "",
    "street": "38 rue Frans Landrain",
    "postalCode": "1970",
    "city": "Wezembeek Oppem",
    "contact1": "Laetitia	Klak",
    "field12": "",
    "tel1": "0477928069",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17021730174",
    "email": "laetitiaklak@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Abi Abdallah",
    "name": "Rose",
    "dateOfBirth": "05/11/2014",
    "school": "",
    "level": "",
    "street": "38 rue Frans Landrain",
    "postalCode": "1970",
    "city": "Wezembeek Oppem",
    "contact1": "Laetitia	Klak",
    "field12": "",
    "tel1": "0477928069",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14051118240",
    "email": "laetitiaklak@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Fakih Lanjri",
    "name": "In�s",
    "dateOfBirth": "10/04/2016",
    "school": "",
    "level": "",
    "street": "Avenue des dames blanches n�92",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Majdouline 	Rouzi",
    "field12": "",
    "tel1": "0484944838",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.10.04-054.67",
    "email": "rouzimajdouline@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Rizoug-Zeghlache",
    "name": "Marwa",
    "dateOfBirth": "03/31/2016",
    "school": "",
    "level": "",
    "street": "Rue jean baptiste du moulin 51",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Mariem	Mazouni",
    "field12": "",
    "tel1": "0488703252",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.03.31-118.17",
    "email": "merydz81@hotmail.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Rizoug-Zeghlache",
    "name": "Nourhane",
    "dateOfBirth": "10/26/2018",
    "school": "",
    "level": "",
    "street": "Jean baptiste 51",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Meriem 	Mazouni",
    "field12": "",
    "tel1": "0488703252",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "18.10.26-174.08",
    "email": "merydz81@hotmail.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Ehring",
    "name": "Andreas",
    "dateOfBirth": "03/22/2015",
    "school": "",
    "level": "",
    "street": "Kastanjebomenlaan 6",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Veerle	Nuyts",
    "field12": "",
    "tel1": "0460/755227",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15032206132",
    "email": "ehringnuyts@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Ehring",
    "name": "Nina",
    "dateOfBirth": "09/14/2010",
    "school": "",
    "level": "",
    "street": "Kastanjebomenlaan 6",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Veerle	Nuyts",
    "field12": "",
    "tel1": "0460/755227",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "10091439074",
    "email": "ehring.nuyts@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Guintsenberg",
    "name": "Robert",
    "dateOfBirth": "11/18/2015",
    "school": "",
    "level": "",
    "street": "Avenue de Tervueren 266 boite 3",
    "postalCode": "1150",
    "city": "Woluwe-Saint-Pierre",
    "contact1": "Igor	Guintsenberg",
    "field12": "",
    "tel1": "0491320832",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "151118-05322",
    "email": "guintsenberg.family@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Dutrieux",
    "name": "Alexandre",
    "dateOfBirth": "12/01/2016",
    "school": "",
    "level": "",
    "street": "Jean Lambottestraat 25",
    "postalCode": "1150",
    "city": "Woluw�-Saint-Pierre",
    "contact1": "S�verine	Kerckx",
    "field12": "",
    "tel1": "0476/37.09.60",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16120127943",
    "email": "scroutchie@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Kiala",
    "name": "Alexandre",
    "dateOfBirth": "03/26/2009",
    "school": "",
    "level": "",
    "street": "26 avenue Gabriel Emile Lebon",
    "postalCode": "1160",
    "city": "Auderghem",
    "contact1": "laititia 	M'BIE MASENGO",
    "field12": "",
    "tel1": "0492 47 64 23",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "090326-52105",
    "email": "laititiambie1302@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Djaroun",
    "name": "Evan",
    "dateOfBirth": "07/15/2016",
    "school": "",
    "level": "",
    "street": "Rue osseghem 166",
    "postalCode": "1080",
    "city": "Bruxelles",
    "contact1": "Amar 	Djaroun",
    "field12": "",
    "tel1": "0489409006",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16071536386",
    "email": "dikon553@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Djaroun",
    "name": "May li",
    "dateOfBirth": "05/22/2014",
    "school": "",
    "level": "",
    "street": "Rue osseghem 166",
    "postalCode": "1080",
    "city": "Bruxelles",
    "contact1": "Amar 	Djaroun",
    "field12": "",
    "tel1": "0489409006",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14052236386",
    "email": "dikon553@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nikov",
    "name": "Angel",
    "dateOfBirth": "09/08/2014",
    "school": "",
    "level": "",
    "street": "Blockmansstraat 11",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Gueorgui	Nikov",
    "field12": "",
    "tel1": "0484 64 84 79",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14090842514",
    "email": "georginikov@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nikova",
    "name": "Mina",
    "dateOfBirth": "09/08/2014",
    "school": "",
    "level": "",
    "street": "Blockmansstraat 11",
    "postalCode": "1150",
    "city": "Brussel",
    "contact1": "Gueorgui	Nikov",
    "field12": "",
    "tel1": "0484 64 84 79",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14090835087",
    "email": "georginikov@hotmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Samani",
    "name": "Daryan",
    "dateOfBirth": "07/23/2014",
    "school": "",
    "level": "",
    "street": "Venelle aux quatre noeuds 70",
    "postalCode": "1150",
    "city": "Woluwe saint-pierre",
    "contact1": "Harika - Behnam	Cahker - Samani",
    "field12": "",
    "tel1": "0488593636",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14072350352",
    "email": "behnamsamani64@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Djaroun",
    "name": "May li",
    "dateOfBirth": "05/22/2014",
    "school": "",
    "level": "",
    "street": "Rue osseghem 166",
    "postalCode": "1080",
    "city": "Bruxelles",
    "contact1": "Amar 	Djaroun",
    "field12": "",
    "tel1": "0489409006",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14052236386",
    "email": "dikon553@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Djaroun",
    "name": "Evan",
    "dateOfBirth": "07/15/2016",
    "school": "",
    "level": "",
    "street": "Rue osseghem 166",
    "postalCode": "1080",
    "city": "Bruxelles",
    "contact1": "Amar 	Djaroun",
    "field12": "",
    "tel1": "0489409006",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16071536386",
    "email": "dikon553@yahoo.fr",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Cogneau",
    "name": "Emilien",
    "dateOfBirth": "01/15/2014",
    "school": "",
    "level": "",
    "street": "Avenue Louis Gribaumont 93",
    "postalCode": "1200",
    "city": "woluwe saint lambert",
    "contact1": "dominique	cogneau",
    "field12": "",
    "tel1": "0492919480",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14011526107",
    "email": "coetdom@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Cogneau",
    "name": "Madeline",
    "dateOfBirth": "01/15/2014",
    "school": "",
    "level": "",
    "street": "Avenue Louis Gribaumont 93",
    "postalCode": "1200",
    "city": "woluwe saint lambert",
    "contact1": "dominique	Cogneau",
    "field12": "",
    "tel1": "0492919480",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14011526008",
    "email": "coetdom@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Sabato",
    "name": "Elisa",
    "dateOfBirth": "05/13/2014",
    "school": "",
    "level": "",
    "street": "Avenue Paul Hymans 83 , A12",
    "postalCode": "1200",
    "city": "Brussels",
    "contact1": "Vardine	Sahakyan",
    "field12": "",
    "tel1": "0483177746",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "14051340647",
    "email": "vardine.sahakyan@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "De Schepper",
    "name": "Jos�phine",
    "dateOfBirth": "03/27/2017",
    "school": "",
    "level": "",
    "street": "Lamoraal van Egmontstraat 34",
    "postalCode": "9000",
    "city": "Gent",
    "contact1": "Laurent	De Schepper",
    "field12": "",
    "tel1": "+32494998450",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "17032711465",
    "email": "l.deschepper@rabotvins.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nguiambo okombi",
    "name": "Amelie",
    "dateOfBirth": "04/08/2015",
    "school": "",
    "level": "",
    "street": "Emmanuelle Mertens 56",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Katia	Tuluka",
    "field12": "",
    "tel1": "0467662584",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "15.04.08-172.57",
    "email": "katiatuluka2@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    },
    {
    "surname": "Nguiambo okombi",
    "name": "Rose",
    "dateOfBirth": "05/28/2016",
    "school": "",
    "level": "",
    "street": "Emmanuel Mertens 56",
    "postalCode": "1150",
    "city": "Bruxelles",
    "contact1": "Katia 	Tuluka",
    "field12": "",
    "tel1": "0467662584",
    "contact2": "",
    "tel2": "",
    "parentSSN": "",
    "parentDOB": "",
    "childSSN": "16.05.27-188.81",
    "email": "katiatuluka2@gmail.com",
    "allergies": "",
    "medicals": "",
    "parentRemarks": "",
    "teamRemarks": "",
    "week1": "",
    "week2": "",
    "week3": "",
    "week4": "",
    "presence": "",
    "balance": "",
    "social": "",
    "totalAmount": "",
    }
    ]

    module.exports = children